# Generated by Django 5.0.4 on 2024-04-08 01:26

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Hotel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=300)),
                ("rating", models.IntegerField(default=0)),
                ("price", models.IntegerField(default=0)),
            ],
        ),
    ]
